// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fnumkflhngagukpzkqya.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZudW1rZmxobmdhZ3VrcHprcXlhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA3NzAzMTksImV4cCI6MjA4NjM0NjMxOX0.TBlxQe91H64S_w_vT4GM4I7U59Txq2tXGQ8h355TFNE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});