// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zjwpcnsmkbestuhalqps.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpqd3BjbnNta2Jlc3R1aGFscXBzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4ODY4NDUsImV4cCI6MjA2OTQ2Mjg0NX0.KGOKsUoS_GfbqaSGjcKKAXmXFBjG74KY1ZLHcpFF18s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});